local config = {
    -- Bot Token generated by @BotFather
    token = "BOT_TOKEN",

    -- Master's username
    master = "MASTER_USERNAME",

    -- Master's userid
    masterid = 000000000,

    -- Timeout for getUpdates method
    timeout = 0,

    -- Limit for getUpdates metho- - d
    limit = 100, 
}
 
return config