return {
	[1] = {
		["isdst"] = false,
		["year"] = 2020,
		["min"] = 7,
		["sec"] = 0,
		["hour"] = 3,
		["yday"] = 322,
		["title"] = "`[Sleep(fake)]` ",
		["wday"] = 3,
		["month"] = 11,
		["day"] = 17,
	},
	[2] = {
		["isdst"] = false,
		["year"] = 2020,
		["min"] = 20,
		["sec"] = 0,
		["hour"] = 3,
		["yday"] = 322,
		["title"] = "`[Sleep (Real)]` ",
		["wday"] = 3,
		["month"] = 11,
		["day"] = 17,
	},
	[3] = {
		["isdst"] = false,
		["year"] = 2020,
		["min"] = 0,
		["sec"] = 0,
		["hour"] = 15,
		["yday"] = 323,
		["title"] = "`[Flight to PEK]` ",
		["wday"] = 4,
		["month"] = 11,
		["day"] = 18,
	},
	[4] = {
		["isdst"] = false,
		["year"] = 2020,
		["min"] = 55,
		["sec"] = 0,
		["hour"] = 14,
		["yday"] = 326,
		["title"] = "`[Flight to CAN]` ",
		["wday"] = 7,
		["month"] = 11,
		["day"] = 21,
	},
	[5] = {
		["isdst"] = false,
		["year"] = 2020,
		["min"] = 0,
		["sec"] = 0,
		["hour"] = 9,
		["yday"] = 348,
		["title"] = "`[ICPC Shanghai 2020]` ",
		["wday"] = 1,
		["month"] = 12,
		["day"] = 13,
	},
}