local config = {
    -- Bot Token generated by @BotFather
    token = "BOT_TOKEN",

    -- Master's username
    master = "MASTER_USERNAME",

    -- Monitor group / user id
    monitor = 000000000,

    -- Timeout for getUpdates method
    timeout = 0,

    -- Limit for getUpdates method
    limit = 100,

    -- Max delay
    ignore = 10,

    -- Enable dolua for guest
    dolua = true,
}

return config