return {
	[8] = {
		["min"] = 0,
		["year"] = 2022,
		["isdst"] = false,
		["yday"] = 75,
		["hour"] = 9,
		["wday"] = 4,
		["month"] = 3,
		["day"] = 16,
		["title"] = "`[下学期重修报名截止]` ",
		["sec"] = 0,
	},
	[1] = {
		["min"] = 7,
		["year"] = 2020,
		["isdst"] = false,
		["yday"] = 322,
		["sec"] = 0,
		["wday"] = 3,
		["title"] = "`[Sleep(fake)]` ",
		["day"] = 17,
		["month"] = 11,
		["hour"] = 3,
	},
	[2] = {
		["min"] = 20,
		["year"] = 2020,
		["isdst"] = false,
		["yday"] = 322,
		["sec"] = 0,
		["wday"] = 3,
		["title"] = "`[Sleep (Real)]` ",
		["day"] = 17,
		["month"] = 11,
		["hour"] = 3,
	},
	[3] = {
		["min"] = 0,
		["year"] = 2020,
		["isdst"] = false,
		["yday"] = 323,
		["sec"] = 0,
		["wday"] = 4,
		["title"] = "`[Flight to PEK]` ",
		["day"] = 18,
		["month"] = 11,
		["hour"] = 15,
	},
	[4] = {
		["min"] = 55,
		["year"] = 2020,
		["isdst"] = false,
		["yday"] = 326,
		["sec"] = 0,
		["wday"] = 7,
		["title"] = "`[Flight to CAN]` ",
		["day"] = 21,
		["month"] = 11,
		["hour"] = 14,
	},
	[5] = {
		["min"] = 0,
		["year"] = 2020,
		["isdst"] = false,
		["yday"] = 348,
		["sec"] = 0,
		["wday"] = 1,
		["title"] = "`[ICPC Shanghai 2020]` ",
		["day"] = 13,
		["month"] = 12,
		["hour"] = 9,
	},
	[6] = {
		["min"] = 0,
		["year"] = 2022,
		["isdst"] = false,
		["yday"] = 71,
		["hour"] = 15,
		["wday"] = 7,
		["month"] = 3,
		["day"] = 12,
		["title"] = "`[J.A.的第五次电路与电子技术考试]` ",
		["sec"] = 0,
	},
	[7] = {
		["min"] = 0,
		["year"] = 2022,
		["isdst"] = false,
		["yday"] = 71,
		["hour"] = 17,
		["wday"] = 7,
		["month"] = 3,
		["sec"] = 0,
		["title"] = "`[J.A.的线上电路与电子技术考试]` ",
		["day"] = 12,
	},
}